services:
  vault:
    image: hashicorp/vault:1.16
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_API_ADDR: "http://${IP_ADDRESS}:8200"
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "wget", "http://127.0.0.1:8200", "--spider", "-q"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: "server -dev"

  vault-config:
    image: hashicorp/vault:1.16
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    volumes:
      - ./:/data
    entrypoint: /bin/sh
    command: "/data/vault-setup-oidc.sh"

  web:
    build: .
    depends_on:
      vault:
        condition: service_healthy
      vault-config:
        condition: service_completed_successfully
    environment:
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    ports:
      - "5000:5000"
    command: "flask run --host=web"
